### ISSUE TITLE
Install info

### ISSUE THREAD

**Issue by psiriders** [fabiocbr75/KeePassFingerprint#1]
Could you update the readme with more information regarding installation etc. How to compile it?

**Comment by fabiocbr75** [comment]
I updated the readme with the requested information.
If you don't want compile and you trust me I attacched my binary to the issue.
[KeePass Password Safe 2.zip](https://github.com/fabiocbr75/KeePassFingerprint/files/2075065/KeePass.Password.Safe.2.zip)

**Comment by sambul13** [comment]
Pls attach here your plugin binary for Keepass 2.41

**Comment by fabiocbr75** [comment]
Hi,
In attach there is all "Keepass 2.35 64bit" with my plugin.
You can use only the plugin (if you have the same version already installed) or all folder.

Bye
Fabio

----------------------------------------

**Comment by sambul13** [comment]
So after update to current KeePass 2,41 it will stop working? Why can't you update it?

**Comment by fabiocbr75** [comment]
First of all you must check if your Version is x86 or x64. I send you the 64 bit Version.
If you want you can recompile with x86/x64 compiler option and use as reference the correct version of keepass.
For now I don't use the new version of keepass and I have only the version sended to you.
Bye

Il 25 febbraio 2019 14:21:43 CET, sambul13 <notifications@github.com> ha scritto:
>So after update to current KeePass 2,41 it will stop working? Why can't
>you update it?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/fabiocbr75/KeePassFingerprint/issues/1#issuecomment-467008634

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.
